lab #9
sofiiaboichun/Labs pull request #1
Opened 2018-12-26 23:04 UTC by sofiiaboichun

Завдання:
У заданому рядку символів підрахувати кількість слів, які починаються групою заданих символів

2018-12-26 23:06 UTC, sofiiaboichun commented
@nechaido review please)

2018-12-27 20:03 UTC, nechaido requested changes
Декомпозировать.

2018-12-27 20:29 UTC, sofiiaboichun commented
@nechaido я декомпозировала

2018-12-27 20:31 UTC, nechaido commented on lab9
> +	vector<string> arr;
Почему эта строка поехала?

2018-12-27 20:33 UTC, sofiiaboichun commented on lab9
> +	vector<string> arr;
теперь?

2018-12-27 20:37 UTC, nechaido commented on lab9
> +    	k=k+1;
А что не так с этой строкой?

2018-12-27 20:43 UTC, sofiiaboichun commented on lab9
> +    	k=k+1;
уже исправила

2018-12-27 21:06 UTC, nechaido commented on lab9
> +        if (tmp.find(a) != std::string::npos)
Оно найдет все слова которіе содержат указанную группу символов а не начинаются с нее.

2018-12-27 21:23 UTC, sofiiaboichun commented on lab9
> +        if (tmp.find(a) != std::string::npos)
А так?

2018-12-27 21:48 UTC, sofiiaboichun commented on lab9
> +        if (tmp.find(a) != std::string::npos)
Я исправила и проверила 
Теперь работает праавильно

2018-12-27 21:48 UTC, nechaido approved these changes
Принято.

2018-12-27 21:56 UTC, closed without merging