lab #8
sofiiaboichun/Labs pull request #2
Opened 2018-12-26 23:17 UTC by sofiiaboichun

Завдання:
Для заданих дійсних квадратних матриць A (n x n) та B (n x n) визначити середнє арифметичне їх М-норм

2018-12-26 23:18 UTC, sofiiaboichun commented
@nechaido review please)

2018-12-27 20:03 UTC, nechaido requested changes
Оформление.

2018-12-27 20:03 UTC, nechaido commented on lab8
> +void array_input2(int **p, int n)
Я говорил сделть функцию ввода обобщенной.

2018-12-27 20:08 UTC, sofiiaboichun commented on lab8
> +void array_input2(int **p, int n)
Значит здесь переделать? Или оставить так?

2018-12-27 20:12 UTC, nechaido commented on lab8
> +void array_input2(int **p, int n)
Переделать и поправить оформление.

2018-12-27 20:28 UTC, sofiiaboichun commented on lab8
> +void array_input2(int **p, int n)
Сделала

2018-12-27 20:29 UTC, nechaido approved these changes
Принято.

2018-12-27 21:57 UTC, closed without merging